"use client";

import {
  Star,
  CheckCircle,
  Sparkles,
  Target,
  Wallet,
  Activity,
  Lightbulb,
  ChevronRight,
  TrendingUp,
  FileDown,
  Share2,
} from "lucide-react";

// --- Constants ---

const HIGHLIGHTS = [
  "Completed 5/7 daily habits consistently.",
  "Under budget by Rs 2,000 for non-essential spending.",
  "Achieved deep sleep goal 6 nights out of 7.",
] as const;

const HABITS = [
  { name: "Deep Work", streak: "12 day streak", percent: 85 },
  { name: "Hydration", streak: "5 day streak", percent: 70 },
  { name: "Reading", streak: "24 day streak", percent: 95 },
] as const;

const GOALS = [
  {
    label: "Q2 Target",
    percent: 75,
    description: "Professional Development Milestone",
    barColor: "bg-[#d2bbff]",
  },
  {
    label: "Marathon Prep",
    percent: 42,
    description: "Accumulated Mileage Goal",
    barColor: "bg-[#ffb95f]",
  },
] as const;

const SPENDING_CATEGORIES = [
  { name: "Travel", percent: 45 },
  { name: "Food & Dining", percent: 30 },
  { name: "Subscriptions", percent: 12 },
] as const;

const HEALTH_TRENDS = [
  {
    label: "Sleep",
    value: "7.4h",
    change: "+15%",
    isPositive: true,
    barHeights: ["40%", "60%", "55%", "80%", "90%"],
    barColor: "bg-[#d2bbff]",
  },
  {
    label: "Exercise",
    value: "240m",
    change: "-4%",
    isPositive: false,
    barHeights: ["70%", "30%", "40%", "0%", "60%"],
    barColor: "bg-[#ffb95f]",
  },
  {
    label: "Weight",
    value: "76.2kg",
    change: "-0.8",
    isPositive: true,
    barHeights: ["85%", "83%", "81%", "82%", "79%"],
    barColor: "bg-[#d2bbff]",
  },
] as const;

const NUDGES = [
  { text: "You haven't exercised in 3 days", isPrimary: true },
  { text: "Review your Q2 professional goals", isPrimary: false },
  { text: "Plan your grocery list for Monday", isPrimary: false },
] as const;

// --- Components ---

function ReportSection({
  icon,
  title,
  titleColor = "text-white",
  children,
  className = "",
}: {
  icon: React.ReactNode;
  title: string;
  titleColor?: string;
  children: React.ReactNode;
  className?: string;
}) {
  return (
    <section
      className={`p-8 rounded-xl bg-[#131b2e] border border-[#4a4455]/10 ${className}`}
    >
      <div className="flex items-center gap-3 mb-6">
        {icon}
        <h2
          className={`text-xl font-[family-name:'Space_Grotesk'] font-semibold uppercase tracking-wider ${titleColor}`}
        >
          {title}
        </h2>
      </div>
      {children}
    </section>
  );
}

// --- Page ---

export default function WeeklyReportPage() {
  return (
    <div className="flex-1 overflow-y-auto bg-[#0b1326]">
      <div className="pt-12 pb-20 px-4 max-w-[700px] mx-auto">
        {/* Header */}
        <header className="mb-12 flex flex-col items-center text-center">
          <h1 className="text-4xl md:text-5xl font-[family-name:'Space_Grotesk'] font-bold text-white tracking-tight mb-2">
            Your Week in Review
          </h1>
          <div className="font-mono text-sm tracking-widest text-[#ccc3d8] uppercase mb-8">
            March 23 -- March 29, 2026
          </div>
          <div className="flex items-center gap-4 px-5 py-2.5 rounded-full bg-[#131b2e] border border-[#4a4455]/10 shadow-lg">
            <div className="w-10 h-10 rounded-full bg-gradient-to-br from-[#7c3aed] to-[#d2bbff] flex items-center justify-center">
              <Sparkles className="h-5 w-5 text-white" />
            </div>
            <div className="text-left">
              <p className="text-[10px] font-mono uppercase tracking-tighter text-[#d2bbff]">
                Intelligence Engine
              </p>
              <p className="text-sm font-medium text-[#dae2fd]">Generated by ATHENA</p>
            </div>
          </div>
        </header>

        <div className="space-y-8">
          {/* Highlights */}
          <ReportSection
            icon={<Star className="h-5 w-5 text-[#ffb95f] fill-current" />}
            title="Highlights"
            className="shadow-[0_20px_40px_-12px_rgba(124,58,237,0.08)]"
          >
            <ul className="space-y-4">
              {HIGHLIGHTS.map((item) => (
                <li key={item} className="flex items-start gap-4">
                  <CheckCircle className="h-5 w-5 text-emerald-400 mt-0.5 fill-current" />
                  <span className="text-[#dae2fd]">{item}</span>
                </li>
              ))}
            </ul>
          </ReportSection>

          {/* Habits Summary */}
          <ReportSection
            icon={<Target className="h-5 w-5 text-[#d2bbff]" />}
            title="Habits Summary"
          >
            <div className="space-y-6 mb-8">
              {HABITS.map((habit) => (
                <div key={habit.name} className="space-y-2">
                  <div className="flex justify-between items-end">
                    <span className="text-sm font-medium text-[#ccc3d8]">{habit.name}</span>
                    <span className="font-mono text-xs text-[#ffb95f]">{habit.streak}</span>
                  </div>
                  <div className="h-2 w-full bg-[#2d3449] rounded-full overflow-hidden">
                    <div
                      className="h-full bg-[#d2bbff] rounded-full"
                      style={{ width: `${habit.percent}%` }}
                    />
                  </div>
                </div>
              ))}
            </div>
            <div className="p-4 rounded-lg bg-[#7c3aed]/10 border-l-2 border-[#d2bbff]">
              <div className="flex items-start gap-3">
                <Sparkles className="h-5 w-5 text-[#d2bbff] shrink-0" />
                <p className="text-sm italic text-[#d2bbff]">
                  &quot;You&apos;re most consistent on weekday mornings. Consider moving your most
                  difficult tasks to the 8 AM slot.&quot;
                </p>
              </div>
            </div>
          </ReportSection>

          {/* Goals Progress */}
          <ReportSection
            icon={<Target className="h-5 w-5 text-[#d2bbff]" />}
            title="Goals Progress"
          >
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {GOALS.map((goal) => (
                <div
                  key={goal.label}
                  className="p-6 rounded-xl bg-[#2d3449]/30 border border-[#4a4455]/10"
                >
                  <div className="flex justify-between mb-4">
                    <span className="text-xs font-mono uppercase text-[#ccc3d8]">
                      {goal.label}
                    </span>
                    <span className="text-lg font-bold text-white">{goal.percent}%</span>
                  </div>
                  <div className="overflow-hidden h-1.5 mb-4 rounded bg-[#2d3449]">
                    <div
                      className={`h-full ${goal.barColor}`}
                      style={{ width: `${goal.percent}%` }}
                    />
                  </div>
                  <p className="text-xs text-[#ccc3d8]">{goal.description}</p>
                </div>
              ))}
            </div>
          </ReportSection>

          {/* Finance Overview */}
          <ReportSection
            icon={<Wallet className="h-5 w-5 text-[#d2bbff]" />}
            title="Finance Overview"
          >
            <div className="flex flex-col md:flex-row gap-10 items-center">
              <div className="flex-1 w-full space-y-4">
                <div className="text-xs font-mono uppercase text-[#ccc3d8]">
                  Spending Comparison
                </div>
                <div className="flex items-end gap-4 h-32 pt-4">
                  <div className="flex-1 flex flex-col items-center gap-2">
                    <div
                      className="w-full bg-[#2d3449] rounded-t-lg"
                      style={{ height: "80%" }}
                    />
                    <span className="text-[10px] font-mono">Last Week</span>
                  </div>
                  <div className="flex-1 flex flex-col items-center gap-2">
                    <div
                      className="w-full bg-gradient-to-t from-[#7c3aed] to-[#d2bbff] rounded-t-lg"
                      style={{ height: "60%" }}
                    />
                    <span className="text-[10px] font-mono text-[#d2bbff]">This Week</span>
                  </div>
                </div>
              </div>
              <div className="flex-1 w-full space-y-4">
                <p className="text-xs font-mono uppercase text-[#ccc3d8] mb-2">Top Categories</p>
                <div className="space-y-3">
                  {SPENDING_CATEGORIES.map((cat) => (
                    <div key={cat.name} className="flex items-center justify-between text-sm">
                      <span className="text-[#dae2fd]">{cat.name}</span>
                      <span className="font-bold text-white">{cat.percent}%</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </ReportSection>

          {/* Health Trends */}
          <ReportSection
            icon={<Activity className="h-5 w-5 text-[#d2bbff]" />}
            title="Health Trends"
          >
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
              {HEALTH_TRENDS.map((trend) => (
                <div key={trend.label} className="space-y-2">
                  <p className="text-[10px] font-mono uppercase text-[#ccc3d8]">{trend.label}</p>
                  <p className="text-2xl font-bold text-white">
                    {trend.value}{" "}
                    <span
                      className={`text-xs font-normal ${trend.isPositive ? "text-emerald-400" : "text-[#ffb4ab]"}`}
                    >
                      {trend.change}
                    </span>
                  </p>
                  <div className="h-12 flex items-end gap-1 opacity-50">
                    {trend.barHeights.map((h, i) => (
                      <div
                        key={i}
                        className={`flex-1 ${trend.barColor} rounded-sm`}
                        style={{ height: h }}
                      />
                    ))}
                  </div>
                </div>
              ))}
            </div>
            <div className="p-4 rounded-lg bg-emerald-500/5 border-l-2 border-emerald-500">
              <p className="text-sm text-emerald-400 flex items-center gap-2">
                <TrendingUp className="h-4 w-4" />
                Your sleep quality improved 15% this week compared to last month.
              </p>
            </div>
          </ReportSection>

          {/* Nudges */}
          <section className="p-8 rounded-xl bg-[#ee9800]/5 border border-[#ee9800]/20 shadow-[0_0_50px_rgba(255,185,95,0.03)]">
            <div className="flex items-center gap-3 mb-6">
              <Lightbulb className="h-5 w-5 text-[#ffb95f] fill-current" />
              <h2 className="text-xl font-[family-name:'Space_Grotesk'] font-semibold text-[#ffb95f] uppercase tracking-wider">
                Athena Nudges
              </h2>
            </div>
            <div className="space-y-4">
              {NUDGES.map((nudge) => (
                <div
                  key={nudge.text}
                  className="flex items-center justify-between p-4 rounded-lg bg-[#171f33] border border-[#4a4455]/10 hover:bg-[#222a3d] transition-colors cursor-pointer group"
                >
                  <div className="flex items-center gap-4">
                    <div
                      className={`w-2 h-2 rounded-full ${nudge.isPrimary ? "bg-[#ffb95f] animate-pulse" : "bg-[#ffb95f]/50"}`}
                    />
                    <span className="text-[#dae2fd]">{nudge.text}</span>
                  </div>
                  <ChevronRight className="h-5 w-5 text-[#ccc3d8] group-hover:translate-x-1 transition-transform" />
                </div>
              ))}
            </div>
          </section>

          {/* CTA Buttons */}
          <div className="flex flex-col sm:flex-row gap-4 pt-10">
            <button className="flex-1 py-4 px-6 rounded-lg bg-gradient-to-r from-[#7c3aed] to-[#d2bbff] text-white font-bold shadow-lg hover:opacity-90 active:scale-[0.98] transition-all flex items-center justify-center gap-2">
              <FileDown className="h-5 w-5" />
              Export PDF
            </button>
            <button className="flex-1 py-4 px-6 rounded-lg border border-[#d2bbff] text-[#d2bbff] font-bold hover:bg-[#d2bbff]/5 active:scale-[0.98] transition-all flex items-center justify-center gap-2">
              <Share2 className="h-5 w-5" />
              Share Report
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
